import Head from "next/head";
import Link from "next/link";
import { useRecoilState } from "recoil";
import { cartState } from "../lib/items";

export default function Layout({ children }) {
  const [cart, setCart] = useRecoilState(cartState);

  return (
    <div>
      <Head>
        <title>Next.js Stripe</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <h1>Next.js Stripe</h1>
        <nav>
          <Link href="/" passHref>
            <a>Home</a>
          </Link>
          <Link href="/cart" passHref>
            <a>Cart {cart.length ? `(${cart.length})` : ""} </a>
          </Link>
        </nav>
      </header>
      <main>{children}</main>
      <style>{`
        header {
            background-color:#FFFFFF;
            height: 100px;
            display: flex;
            flex-flow: row no-wrap;
            box-shadow: 0 2px 1px #dedede;
        }
        header h1 {
            margin: auto 40px;
            color: #6F00FF;
        }
        header nav {
            height: 100%;
            background-color: transparent;
            flex: 1 0 auto;
            display: flex;
            flex-flow: row no-wrap;
            justify-content: flex-end;
            align-items: center;
        }
        header nav a {
            margin: 10px 10px;
            padding: 10px 20px;
            background-color: #6F00FF;
            font-weight: bold;
            color: #ffffff;
        }
        header nav a:hover{
            background-color: #FFFFFF;
            font-weight: bold;
            color: #000000;
        }
      `}</style>
    </div>
  );
}
